const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Tee-Shirt',
      slug: 'nike-tee-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1000,
      CountInStock: 13,
      brand: 'Nike',
      rating: 5,
      numReviews: 9,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit Tee-Shirt',
      slug: 'adidas-fit-tee-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1000,
      CountInStock: 0,
      brand: 'Adidas',
      rating: 3.9,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'American Eagle Jeans',
      slug: 'american-eagle-jeans',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 1400,
      CountInStock: 8,
      brand: 'American Eagle',
      rating: 4.7,
      numReviews: 12,
      description: 'high quality jeans',
    },
    {
      _id: '4',
      name: 'Levis Jeans',
      slug: 'levis-jeans',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1600,
      CountInStock: 8,
      brand: 'Levis',
      rating: 4.8,
      numReviews: 8,
      description: 'high quality jeans',
    },
  ],
};
export default data;
